export type UtilityLocale = 'en' | 'zh' | 'ja'
export const utilityCopy = {
  en: {
    lang: 'en-US', model: 'Model / pricing preset', custom: 'Custom rates (unverified)', tokens: 'Recorded tokens', rates: 'Rates · USD per million tokens',
    categories: { input: 'Base input (excluding cache)', output: 'Output', cacheRead: 'Cache read', cacheWrite5m: '5-minute cache write', cacheWrite1h: '1-hour cache write' },
    schedule: 'Monthly scenario', sessions: 'Summaries per working day', days: 'Working days per month', calculate: 'Calculate estimate', example: 'Try public example', reset: 'Reset',
    estimate: 'Estimated API-equivalent cost', total: 'Per entered summary', monthly: 'Per working month', breakdown: 'Token cost breakdown', category: 'Category', subtotal: 'Subtotal (USD)',
    reviewed: 'Preset rates checked', source: 'Official pricing', customNotice: 'You supplied these rates; they are not verified list prices.',
    boundary: 'Not a bill or a prediction of Pro/Max capacity. Excludes provider modifiers and non-token charges. Monthly cost assumes the same usage repeats; a daily total should use one summary per day.',
    jsonl: 'Claude Code JSONL', file: 'Select a local JSONL file (up to 5 MiB)', count: 'Count recorded tokens', reading: 'Reading locally…',
    local: 'No upload, API key or installation. Tool input stays in this page’s memory; reset or reload clears it. Normal documentation asset requests still occur.',
    counterResult: 'Recorded usage totals', records: 'Distinct recorded assistant messages', cacheWrite: 'Cache creation (all lifetimes)', totalTokens: 'Total recorded tokens',
    diagnostics: 'Coverage and deduplication', duplicates: 'Coalesced duplicate message IDs', missingIds: 'Usage rows without IDs (cannot deduplicate)', missingUsage: 'Assistant rows missing usage', invalidUsage: 'Invalid usage rows skipped', malformedLines: 'Malformed JSON lines skipped', ignoredLines: 'Non-assistant / unsupported rows skipped', inconsistentCache: 'Inconsistent cache totals (larger total used)',
    counterBoundary: 'This sums saved usage fields, not tokens in pasted prompt text or live account quota. Repeated context counts again per API call. Missing cache fields count as zero here, not proof that caching was absent.',
    errors: { tokens: 'Enter nonnegative whole token counts within the safe integer range. Empty fields are not zero.', rates: 'Enter a finite nonnegative rate for every category, in USD per million tokens.', schedule: 'Use 1–1000 summaries per day and 1–31 working days per month.', overflow: 'The result exceeds the supported numeric range. Reduce the input.', size: 'Input exceeds 5 MiB. Choose a smaller JSONL file or use the desktop app.', lines: 'Input exceeds 20,000 lines. Use a smaller excerpt or the desktop app.', format: 'No usable assistant message.usage records found. Paste Claude Code JSONL, not /usage text or a prompt.', file: 'Could not read this file. Select a readable local JSONL file and try again.' },
  },
  zh: {
    lang: 'zh-CN', model: '模型 / 价格预设', custom: '自定义价格（未核验）', tokens: '记录的 Token', rates: '价格 · 美元 / 百万 Token',
    categories: { input: '普通输入（不含缓存）', output: '输出', cacheRead: '缓存读取', cacheWrite5m: '5 分钟缓存写入', cacheWrite1h: '1 小时缓存写入' },
    schedule: '月度情景估算', sessions: '每个工作日的汇总次数', days: '每月工作日', calculate: '计算估算成本', example: '试用公开样例', reset: '重置',
    estimate: 'API 等价成本估算', total: '本次输入的汇总', monthly: '每个工作月', breakdown: 'Token 成本明细', category: '类别', subtotal: '小计（美元）',
    reviewed: '预设价格核对日期', source: '官方定价', customNotice: '这些价格由你填写，不是已核验的官方预设。',
    boundary: '不是账单，也不能预测 Pro/Max 套餐容量；不含供应商调整与非 Token 费用。月度估算假设相同用量重复发生；输入一天的总量时，每日汇总次数应设为 1。',
    jsonl: 'Claude Code JSONL', file: '选择本地 JSONL 文件（最多 5 MiB）', count: '统计记录的 Token', reading: '正在本地读取…',
    local: '无需上传、API Key 或安装。工具输入只保留在当前页面内存，重置或刷新即清除；文档资源本身仍会产生正常网络请求。',
    counterResult: '记录用量汇总', records: '去重后的 assistant 用量记录', cacheWrite: '缓存创建（全部有效期）', totalTokens: '记录的 Token 总数',
    diagnostics: '覆盖范围与去重', duplicates: '合并的重复消息 ID', missingIds: '缺少 ID 的用量行（无法去重）', missingUsage: '缺少 usage 的 assistant 行', invalidUsage: '跳过的无效用量行', malformedLines: '跳过的错误 JSON 行', ignoredLines: '跳过的非 assistant / 不支持行', inconsistentCache: '缓存总量不一致（取较大值）',
    counterBoundary: '统计保存的 usage 字段，不估算粘贴提示词的 Token，也不读取实时账户额度。重复上下文会按调用重复计数；缺少缓存字段在此按 0 汇总，不代表实际没有缓存。',
    errors: { tokens: '每项 Token 必须是安全整数范围内的非负整数，空输入不视为 0。', rates: '请为每项填写有限的非负价格，单位为美元 / 百万 Token。', schedule: '每日汇总次数应为 1–1000，每月工作日应为 1–31。', overflow: '计算结果超出数值范围，请减少输入。', size: '输入超过 5 MiB，请选择更小的 JSONL 文件或使用桌面应用。', lines: '输入超过 20,000 行，请使用较小片段或桌面应用。', format: '未找到可用的 assistant message.usage 记录；请粘贴 Claude Code JSONL，不是 /usage 文本或提示词。', file: '无法读取文件，请选择可读取的本地 JSONL 文件后重试。' },
  },
  ja: {
    lang: 'ja-JP', model: 'モデル / 料金プリセット', custom: 'カスタム料金（未検証）', tokens: '記録されたトークン', rates: '料金 · USD / 100 万トークン',
    categories: { input: '通常入力（キャッシュを除く）', output: '出力', cacheRead: 'キャッシュ読み込み', cacheWrite5m: '5 分キャッシュ書き込み', cacheWrite1h: '1 時間キャッシュ書き込み' },
    schedule: '月間シナリオ', sessions: '稼働日あたりの集計回数', days: '月あたりの稼働日', calculate: '推定コストを計算', example: '公開サンプルを試す', reset: 'リセット',
    estimate: 'API 相当の推定コスト', total: '入力した集計 1 回分', monthly: '稼働月あたり', breakdown: 'トークンコストの内訳', category: '区分', subtotal: '小計（USD）',
    reviewed: 'プリセット料金の確認日', source: '公式料金', customNotice: '入力した料金です。検証済みの公式プリセットではありません。',
    boundary: '請求書でも Pro/Max の利用可能量の予測でもありません。プロバイダーの調整やトークン以外の料金は含みません。月額は同じ使用量の反復を仮定します。1 日の合計を入力した場合、集計回数は 1 にしてください。',
    jsonl: 'Claude Code JSONL', file: 'ローカル JSONL ファイルを選択（最大 5 MiB）', count: '記録トークンを集計', reading: 'ローカルで読み込み中…',
    local: 'アップロード、API キー、インストールは不要です。入力はこのページのメモリーだけに保持し、リセットや再読み込みで消去します。ドキュメント資産の通常の通信は発生します。',
    counterResult: '記録使用量の集計', records: '重複排除した assistant 使用量レコード', cacheWrite: 'キャッシュ作成（全有効期間）', totalTokens: '記録トークン総数',
    diagnostics: '対象範囲と重複排除', duplicates: '統合した重複メッセージ ID', missingIds: 'ID のない使用量行（重複排除不可）', missingUsage: 'usage のない assistant 行', invalidUsage: 'スキップした無効な使用量行', malformedLines: 'スキップした不正 JSON 行', ignoredLines: 'assistant 以外 / 未対応の行', inconsistentCache: '不一致のキャッシュ総数（大きい値を採用）',
    counterBoundary: '保存済み usage の集計であり、貼り付けたプロンプトのトークン推定やリアルタイムのアカウント上限ではありません。同じ文脈も呼び出しごとに再集計します。欠落したキャッシュ項目は 0 としますが、実際にキャッシュがなかった証拠ではありません。',
    errors: { tokens: '各トークン数に安全な整数範囲内の非負整数を入力してください。空欄は 0 ではありません。', rates: '各区分に有限の非負料金を入力してください。単位は USD / 100 万トークンです。', schedule: '1 日の集計回数は 1–1000、月の稼働日は 1–31 にしてください。', overflow: '結果が対応する数値範囲を超えました。入力を減らしてください。', size: '5 MiB を超えています。小さい JSONL ファイルかデスクトップアプリを利用してください。', lines: '20,000 行を超えています。小さい抜粋かデスクトップアプリを利用してください。', format: '利用可能な assistant message.usage がありません。/usage テキストやプロンプトではなく Claude Code JSONL を貼り付けてください。', file: 'ファイルを読めません。読み込み可能なローカル JSONL ファイルを選び直してください。' },
  },
}
